### ISSUE TITLE
PSP Games not working in RPi3 Lakka 2.1 stable release build

### ISSUE THREAD

**Issue by jds40net** [libretro/Lakka-LibreELEC#316]
Various PSP games run on my RPi3 using Lakka 2.1-rc5. They don’t in the more recent 2.1 stable release (11/26/2017). Video doesn't render with these games. Here are some troubleshooting results:

"Ok, confirmed that the problem is ppsspp_libretro.so of the stabile.

 I solved extracting ppsspp_libretro.so from the RC5 version, I put it in /storage/cores, and I modified the path inside the playlist Sony - PlayStation Portable.lpl replace it from /tmp/cores to storage/cores.

All works perfectly."

Here's a link to the original thread in the lakka forum:

https://forums.libretro.com/t/psp-games-not-working-in-rpi3-lakka-2-1-stable-release-build/13509

**Comment by Kivutar** [comment]
@gouchi tested it on x86_64 and the problem doesn't happen there. It may affect only ARM boards.

**Comment by Kivutar** [comment]
I confirm this bug. When launching a psp rom, RA will just exit cleanly, without segfault.

**Comment by kivutar** [comment]
Fixed by https://github.com/libretro/Lakka-LibreELEC/commit/583afe6afb7f786863fa2961929a71ddf20d0549

**Comment by jds40net** [comment]
The bug below was marked as fixed and the thread "closed":


https://github.com/libretro/Lakka-LibreELEC/issues/316


I have just loaded Lakka-RPi2.arm-2.1.1.img.gz dated 6/25/2018. I'm afraid the bug persists.  With this build, video does not render on various games that run successfully on my RPi3 using Lakka 2.1-rc5.


Please can you investigate and reopen the bug report if needed.  Thanks.


-----Original Message-----
